# Generated by Django 4.2.2 on 2023-06-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettable',
            name='a1',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pettable',
            name='a2',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pettable',
            name='a3',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pettable',
            name='prompt1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pettable',
            name='prompt2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pettable',
            name='prompt3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
