# Generated by Django 4.2.2 on 2023-06-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_pettable_prompt1_alter_pettable_prompt2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettable',
            name='energy_level',
            field=models.CharField(choices=[('low', 'Very Energetic'), ('moderate', 'Medium'), ('high', 'Chill')], default='low', max_length=50),
        ),
    ]
