# Generated by Django 4.2.2 on 2023-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pettable_energy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionpreferences',
            name='energyLevel',
            field=models.CharField(choices=[('low', 'Very Energetic'), ('moderate', 'Medium'), ('high', 'Chill')], default='low', max_length=50),
        ),
    ]
