# Generated by Django 4.2.2 on 2023-06-22 14:56

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_petimage_photo_petimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='petimage',
            name='photo',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='pets/'),
        ),
    ]
