# Generated by Django 4.2.2 on 2023-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_petimage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettable',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='healthStatus',
            field=models.CharField(choices=[('good health', 'Good Health'), ('needs medication', 'Needs Medication'), ('disabled', 'Disabled')], default='good health', max_length=250),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='sociability',
            field=models.CharField(choices=[('introvert', 'Introvert'), ('extrovert', 'Extrovert'), ('both', 'Both')], default='introvert', max_length=40),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='vaccinationInformation',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Fully Vaccinated')], default='N', max_length=1),
        ),
    ]
