# Generated by Django 4.2.2 on 2023-06-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_adoptionpreferences_energylevel'),
        ('main_app', '0009_alter_pettable_activity_level_alter_pettable_gender_and_more'),
    ]

    operations = [
    ]
