# Generated by Django 4.2.2 on 2023-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_adoptionpreferences_activitylevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='activityLevel',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='energyLevel',
            field=models.CharField(choices=[('low', 'Very Energetic'), ('moderate', 'Medium'), ('high', 'Chill')], default='low', max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='small', max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='sociability',
            field=models.CharField(choices=[('introvert', 'Introvert'), ('extrovert', 'Extrovert'), ('both', 'Both')], default='both', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=50),
        ),
    ]
