# Generated by Django 4.2.2 on 2023-06-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_pettable_prompt1_alter_pettable_prompt2_and_more'),
        ('main_app', '0012_alter_adoptionpreferences_activitylevel_and_more'),
    ]

    operations = [
    ]
