# Generated by Django 4.2.2 on 2023-06-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_adoptionpreferences_activitylevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmatch',
            name='matchStatus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='energy_level',
            field=models.CharField(choices=[('low', 'Very Energetic'), ('moderate', 'Medium'), ('high', 'Chill')], default='low', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='prompt1',
            field=models.CharField(choices=[('a', 'My catchphrase is'), ('b', 'My most embarrassing moment'), ('c', 'If I was a character from a movie or a book, I would be'), ('d', 'A time when I was surprisingly clever '), ('e', "My favorite 'toy' that isn't actually a toy"), ('f', "When I want my human's attention I"), ('g', "I show I'm happy by"), ('h', 'If I could talk for 60 seconds I would say'), ('i', 'When I see my reflection in the mirror I'), ('j', 'An activity I could do for hours is'), ('k', 'My superpower would be'), ('l', 'My weirdest habit is'), ('m', 'When I meet new people or dogs I'), ('n', 'If I had a human job it would be'), ('o', 'My theme song would be'), ('p', 'I salivate over'), ('q', 'I was really brave when'), ('r', 'When I see a squirrel I'), ('s', 'I had an unusual friendship with'), ('t', 'My dream day')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='sociability',
            field=models.CharField(choices=[('introvert', 'Introvert'), ('extrovert', 'Extrovert'), ('both', 'Both')], default='introvert', max_length=255),
        ),
    ]
