# Generated by Django 4.2.2 on 2023-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20230623_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionpreferences',
            name='liked_pets',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='main_app.pettable'),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
