# Generated by Django 4.2.2 on 2023-06-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_adoptionpreferences_liked_pets_alter_pettable_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettable',
            name='monthlyCost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
