# Generated by Django 4.2.2 on 2023-06-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_petimage_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petimage',
            old_name='pet_id',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='petmatch',
            old_name='pet_id',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='petmatch',
            old_name='user_id',
            new_name='user',
        ),
    ]
