# Generated by Django 4.2.2 on 2023-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_rename_pet_id_petimage_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.CharField(choices=[('a', 'My catchphrase is'), ('b', 'My most embarrassing moment'), ('c', 'If I was a character from a movie or a book, I would be'), ('d', 'A time when I was surprisingly clever '), ('e', "My favorite 'toy' that isn't actually a toy"), ('f', "When I want my human's attention I"), ('g', "I show I'm happy by"), ('h', 'If I could talk for 60 seconds I would say'), ('i', 'When I see my reflection in the mirror I'), ('j', 'An activity I could do for hours is'), ('k', 'My superpower would be'), ('l', 'My weirdest habit is'), ('m', 'When I meet new people or dogs I'), ('n', 'If I had a human job it would be'), ('o', 'My theme song would be'), ('p', 'I salivate over'), ('q', 'I was really brave when'), ('r', 'When I see a squirrel I'), ('s', 'I had an unusual friendship with'), ('t', 'My dream day')], default='a', max_length=100),
        ),
    ]
