# Generated by Django 4.2.2 on 2023-06-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_petmatch_matchstatus_and_more'),
        ('main_app', '0020_alter_prompt_prompt'),
    ]

    operations = [
    ]
