# Generated by Django 4.2.2 on 2023-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_merge_20230626_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
        migrations.AlterField(
            model_name='petmatch',
            name='matchStatus',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='energy_level',
            field=models.CharField(choices=[('low', 'Very Energetic'), ('moderate', 'Medium'), ('high', 'Chill')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='sociability',
            field=models.CharField(choices=[('introvert', 'Introvert'), ('extrovert', 'Extrovert'), ('both', 'Both')], default='introvert', max_length=40),
        ),
    ]
