# Generated by Django 4.2.2 on 2023-06-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_redirectmodel_remove_pettable_prompt1_and_more'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='RedirectModel',
    #     ),
    #     migrations.RemoveField(
    #         model_name='pettable',
    #         name='prompt1',
    #     ),
    # ]
