# Generated by Django 4.2.2 on 2023-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_delete_redirectmodel_remove_pettable_prompt1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedirectModel',
        ),
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
        # migrations.AlterField(
        #     model_name='userdetails',
        #     name='adopter',
        #     field=models.BooleanField(blank=True, default=False),
        # ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='firstName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lastName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
