# Generated by Django 4.2.2 on 2023-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_remove_pettable_prompt1_alter_userdetails_adopter'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
        migrations.AlterField(
            model_name='userdetails',
            name='adopter',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
