# Generated by Django 4.2.2 on 2023-06-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_merge_20230626_1026'),
        ('main_app', '0027_remove_pettable_prompt1_alter_userdetails_adopter'),
    ]

    operations = [
    ]
