# Generated by Django 4.2.2 on 2023-06-26 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0028_merge_20230626_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmatch',
            name='matchStatus',
        ),
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
        migrations.AddField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='activityLevel',
            field=models.CharField(choices=[('low', 'Less than an hour'), ('moderate', 'One to two hours'), ('high', 'Two hours minimum')], default='low', max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='energyLevel',
            field=models.CharField(choices=[('low', 'Very calm'), ('moderate', 'Moderate energy level'), ('high', 'High energy')], default='low', max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='size',
            field=models.CharField(choices=[('S', 'Small, up to 9kg'), ('M', 'Medium, up to 27kg'), ('L', 'Large, up to 45kg'), ('XL', 'Large, over 45kg')], default='small', max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='sociability',
            field=models.CharField(choices=[('very', 'Very sociable, loves both dogs and people'), ('somewhat', 'Somewhat sociable, selectively interacts'), ('hardly', 'Not very sociable, prefers to keep a distance'), ('not', 'Not sociable, avoids interaction when possible')], default='both', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('low', 'Less than an hour'), ('moderate', 'One to two hours'), ('high', 'Two hours minimum')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('low', 'Very calm'), ('moderate', 'Moderate energy level'), ('high', 'High energy')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='healthStatus',
            field=models.CharField(blank=True, choices=[('good health', 'Good Health'), ('needs medication', 'Needs Medication'), ('disabled', 'Disabled')], default='good health', max_length=250),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='monthlyCost',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small, up to 9kg'), ('M', 'Medium, up to 27kg'), ('L', 'Large, up to 45kg'), ('XL', 'Large, over 45kg')], default='S', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='sociability',
            field=models.CharField(blank=True, choices=[('very', 'Very sociable, loves both dogs and people'), ('somewhat', 'Somewhat sociable, selectively interacts'), ('hardly', 'Not very sociable, prefers to keep a distance'), ('not', 'Not sociable, avoids interaction when possible')], default='introvert', max_length=40),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='vaccinationInformation',
            field=models.CharField(blank=True, choices=[('N', 'No'), ('Y', 'Fully Vaccinated')], default='N', max_length=1),
        ),
    ]
