# Generated by Django 4.2.2 on 2023-06-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_remove_pettable_prompt1_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
        migrations.AlterField(
            model_name='pettable',
            name='healthStatus',
            field=models.CharField(blank=True, choices=[('good health', 'Good Health'), ('needs medication', 'Needs Medication'), ('disabled', 'Disabled')], default='disabled', max_length=250),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='sociability',
            field=models.CharField(blank=True, choices=[('very', 'Very sociable, loves both dogs and people'), ('somewhat', 'Somewhat sociable, selectively interacts'), ('hardly', 'Not very sociable, prefers to keep a distance'), ('not', 'Not sociable, avoids interaction when possible')], default='very', max_length=40),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='vaccinationInformation',
            field=models.CharField(blank=True, choices=[('N', 'No'), ('Y', 'Fully Vaccinated')], default='Y', max_length=1),
        ),
    ]
