# Generated by Django 4.2.2 on 2023-06-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_remove_pettable_prompt1_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='activityLevel',
            field=models.CharField(choices=[('Low', 'Less than an hour'), ('Moderate', 'One to two hours'), ('High', 'Two hours minimum')], default='low', max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='energyLevel',
            field=models.CharField(choices=[('Low', 'Very calm'), ('Moderate', 'Moderate energy level'), ('High', 'High energy')], default='low', max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='size',
            field=models.CharField(choices=[('Small', 'Small, up to 9kg'), ('Medium', 'Medium, up to 27kg'), ('Large', 'Large, up to 45kg'), ('XL', 'Large, over 45kg')], default='small', max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionpreferences',
            name='sociability',
            field=models.CharField(choices=[('Very sociable', 'Very sociable, loves both dogs and people'), ('Somewhat sociable', 'Somewhat sociable, selectively interacts'), ('Hardly sociable', 'Not very sociable, prefers to keep a distance'), ('Not sociable', 'Not sociable, avoids interaction when possible')], default='both', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Low', 'Less than an hour'), ('Moderate', 'One to two hours'), ('High', 'Two hours minimum')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('Low', 'Very calm'), ('Moderate', 'Moderate energy level'), ('High', 'High energy')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='healthStatus',
            field=models.CharField(blank=True, choices=[('Good health', 'Good Health'), ('Needs medication', 'Needs Medication'), ('Disabled', 'Disabled')], default='good health', max_length=250),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small, up to 9kg'), ('Medium', 'Medium, up to 27kg'), ('Large', 'Large, up to 45kg'), ('XL', 'Large, over 45kg')], default='S', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='sociability',
            field=models.CharField(blank=True, choices=[('Very sociable', 'Very sociable, loves both dogs and people'), ('Somewhat sociable', 'Somewhat sociable, selectively interacts'), ('Hardly sociable', 'Not very sociable, prefers to keep a distance'), ('Not sociable', 'Not sociable, avoids interaction when possible')], default='introvert', max_length=40),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='vaccinationInformation',
            field=models.CharField(blank=True, choices=[('Not vaccinated', 'No'), ('Vaccinated', 'Fully Vaccinated')], default='N', max_length=20),
        ),
    ]
