<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-26 19:43
=======
# Generated by Django 4.2.2 on 2023-06-27 08:13
>>>>>>> development

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('main_app', '0031_remove_pettable_prompt1_alter_pettable_healthstatus_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
=======
        ('main_app', '0031_remove_pettable_prompt1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettable',
            name='prompt1',
        ),
>>>>>>> development
    ]
