# Generated by Django 4.2.2 on 2023-06-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_remove_pettable_prompt1'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
        migrations.AlterField(
            model_name='pettable',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Less than an hour'), ('moderate', 'One to two hours'), ('high', 'Two hours minimum')], default='low', max_length=255),
        ),
    ]
