# Generated by Django 4.2.2 on 2023-06-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_remove_pettable_prompt1_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
        migrations.AlterField(
            model_name='pettable',
            name='energy_level',
            field=models.CharField(choices=[('low', 'Very calm'), ('moderate', 'Moderate energy level'), ('high', 'High energy')], default='low', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='healthStatus',
            field=models.CharField(choices=[('good health', 'Good Health'), ('needs medication', 'Needs Medication'), ('disabled', 'Disabled')], default='disabled', max_length=250),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='size',
            field=models.CharField(choices=[('S', 'Small, up to 9kg'), ('M', 'Medium, up to 27kg'), ('L', 'Large, up to 45kg'), ('XL', 'Large, over 45kg')], default='small', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='sociability',
            field=models.CharField(choices=[('very', 'Very sociable, loves both dogs and people'), ('somewhat', 'Somewhat sociable, selectively interacts'), ('hardly', 'Not very sociable, prefers to keep a distance'), ('not', 'Not sociable, avoids interaction when possible')], default='very', max_length=255),
        ),
        migrations.AlterField(
            model_name='pettable',
            name='vaccinationInformation',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Fully Vaccinated')], default='Y', max_length=1),
        ),
    ]
