# Generated by Django 4.2.2 on 2023-06-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_remove_pettable_prompt1_and_more'),
        ('main_app', '0033_alter_pettable_activity_level_and_more'),
        ('main_app', '0034_remove_pettable_prompt1_alter_pettable_energy_level_and_more'),
    ]

    operations = [
    ]
