# Generated by Django 4.2.2 on 2023-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_remove_pettable_prompt1_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='pettable',
        #     name='prompt1',
        # ),
        migrations.AddField(
            model_name='petmatch',
            name='matchStatus',
            field=models.BooleanField(default=False),
        ),
    ]
